---
abstract: 'module to during a test run convert on the fly Selenese IDE html to perl tests'
author:
  - 'Andy Brown <setitesuk@gmail.com>'
build_requires:
  JSON: 0
  Test::Exception: 0
  Test::MockObject: 0
configure_requires:
  Module::Build: 0.3603
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Selenium-Conversion-IDE
provides:
  Test::WWW::Selenium::Conversion::IDE:
    file: lib/Test/WWW/Selenium/Conversion/IDE.pm
    version: 0.4
requires:
  Carp: 0
  English: 0
  Exporter: 0
  Readonly: 0
  Test::More: 0.8
  Test::WWW::Selenium: 0
  XML::LibXML: 0
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
version: 0.4
